name: 'Update ClickUp Status'
description: 'Update ClickUp Status'
inputs:
  team-id:
    description: 'Team ID'
    required: true
  status:
    description: 'Requested Status'
    required: true    
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'dist/index.js'
